from tkinter import *
from tkinter import ttk
from tkinter import font
from funciones import *


class T1(Frame):
    def __init__(self, geom):
        Frame.__init__(self, )
        self.hig, self.wid = geom

        # Interes Total
        self.it1 = ttk.Label(self, text='Interes Total', font=font.Font(size=12))
        self.it1.place(x=0, y=20)
        self.it2 = ttk.Label(self, text='Saldo inicial')
        self.it2.place(x=0, y=80)
        self.it3 = ttk.Label(self, text='Saldo final')
        self.it3.place(x=0, y=100)
        self.it4 = ttk.Entry(self, textvariable=0, width=13)
        self.it4.place(x=90, y=80)
        self.it5 = ttk.Entry(self, textvariable=5, width=13)
        self.it5.place(x=90, y=100)
        self.it6 = ttk.Button(self, text='Calcular')
        self.it6.place(x=0, y=130)
        self.it7 = ttk.Label(self, text='Resultado')
        self.it7.place(x=90, y=133)

        # Tasa de Interes
        self.tdi1 = ttk.Label(self, text='Tasa de Interes', font=font.Font(size=12))
        self.tdi1.place(x=200, y=20)
        self.tdi2 = ttk.Label(self, text='Interes:')
        self.tdi2.place(x=200, y=80)
        self.tdi3 = ttk.Label(self, text='Credito')
        self.tdi3.place(x=200, y=100)
        self.tdi4 = ttk.Entry(self, textvariable=0, width=13)
        self.tdi4.place(x=290, y=80)
        self.tdi5 = ttk.Entry(self, textvariable=5, width=13)
        self.tdi5.place(x=290, y=100)
        self.tdi6 = ttk.Button(self, text='Calcular')
        self.tdi6.place(x=200, y=130)
        self.tdi7 = ttk.Label(self, text='Resultado')
        self.tdi7.place(x=290, y=133)

        # Valor Futuro Interes Simple
        self.vfis1 = ttk.Label(self, text='Valor Futuro', font=font.Font(size=12))
        self.vfis1.place(x=400, y=20)
        self.vfis2 = ttk.Label(self, text='Interes Simple', font=font.Font(size=12))
        self.vfis2.place(x=400, y=40)
        self.vfis3 = ttk.Label(self, text='VP:')
        self.vfis3.place(x=400, y=80)
        self.vfis4 = ttk.Label(self, text='i')
        self.vfis4.place(x=400, y=100)
        self.vfis4 = ttk.Label(self, text='n')
        self.vfis4.place(x=400, y=120)
        self.vfis5 = ttk.Entry(self, textvariable=0, width=13)
        self.vfis5.place(x=490, y=80)
        self.vfis6 = ttk.Entry(self, textvariable=5, width=13)
        self.vfis6.place(x=490, y=100)
        self.vfis6 = ttk.Entry(self, textvariable=8, width=13)
        self.vfis6.place(x=490, y=120)
        self.vfis7 = ttk.Button(self, text='Calcular')
        self.vfis7.place(x=400, y=150)
        self.vfis8 = ttk.Label(self, text='Resultado')
        self.vfis8.place(x=490, y=153)

        # Valor Futuro Interes Compuesto
        self.vfic1 = ttk.Label(self, text='Valor Futuro', font=font.Font(size=12))
        self.vfic1.place(x=600, y=20)
        self.vfic2 = ttk.Label(self, text='Interes Compuesto', font=font.Font(size=12))
        self.vfic2.place(x=600, y=40)
        self.vfic3 = ttk.Label(self, text='VP:')
        self.vfic3.place(x=600, y=80)
        self.vfic4 = ttk.Label(self, text='i')
        self.vfic4.place(x=600, y=100)
        self.vfic4 = ttk.Label(self, text='n')
        self.vfic4.place(x=600, y=120)
        self.vfic5 = ttk.Entry(self, textvariable=0, width=13)
        self.vfic5.place(x=690, y=80)
        self.vfic6 = ttk.Entry(self, textvariable=5, width=13)
        self.vfic6.place(x=690, y=100)
        self.vfic6 = ttk.Entry(self, textvariable=8, width=13)
        self.vfic6.place(x=690, y=120)
        self.vfic7 = ttk.Button(self, text='Calcular')
        self.vfic7.place(x=600, y=150)
        self.vfic8 = ttk.Label(self, text='Resultado')
        self.vfic8.place(x=690, y=153)

        # Conversion tasa de interes simple

        self.ctis1 = ttk.Label(self, text='Conversion tasa de', font=font.Font(size=12))
        self.ctis1.place(x=0, y=220)
        self.ctis2 = ttk.Label(self, text='interes simple', font=font.Font(size=12))
        self.ctis2.place(x=0, y=240)
        self.ctis3 = ttk.Label(self, text='Interes Periodo1')
        self.ctis3.place(x=0, y=280)
        self.ctis4 = ttk.Label(self, text='Perdiodo 1')
        self.ctis4.place(x=0, y=300)
        self.ctis5 = ttk.Label(self, text='Periodo 2')
        self.ctis5.place(x=0, y=320)
        self.ctis6 = ttk.Entry(self, textvariable=0, width=13)
        self.ctis6.place(x=90, y=280)
        self.ctis7 = ttk.Entry(self, textvariable=5, width=13)
        self.ctis7.place(x=90, y=300)
        self.ctis8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctis8.place(x=90, y=320)
        self.ctis9 = ttk.Button(self, text='Calcular')
        self.ctis9.place(x=0, y=350)
        self.ctis10 = ttk.Label(self, text='Resultado')
        self.ctis10.place(x=90, y=353)

        # Conversion tasa de interes compuesto

        self.ctic1 = ttk.Label(self, text='Conversion tasa de', font=font.Font(size=12))
        self.ctic1.place(x=200, y=220)
        self.ctic2 = ttk.Label(self, text='interes compuesto', font=font.Font(size=12))
        self.ctic2.place(x=200, y=240)
        self.ctic3 = ttk.Label(self, text='Interes periodo1')
        self.ctic3.place(x=200, y=280)
        self.ctic4 = ttk.Label(self, text='Periodo 1')
        self.ctic4.place(x=200, y=300)
        self.ctic5 = ttk.Label(self, text='Periodo 2')
        self.ctic5.place(x=200, y=320)
        self.ctic6 = ttk.Entry(self, textvariable=0, width=13)
        self.ctic6.place(x=290, y=280)
        self.ctic7 = ttk.Entry(self, textvariable=5, width=13)
        self.ctic7.place(x=290, y=300)
        self.ctic8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctic8.place(x=290, y=320)
        self.ctic9 = ttk.Button(self, text='Calcular')
        self.ctic9.place(x=200, y=350)
        self.ctic10 = ttk.Label(self, text='Resultado')
        self.ctic10.place(x=290, y=353)
