from tkinter import *
from tkinter import ttk
from tkinter import font
from funciones import *


class T2(Frame):
    def __init__(self, geom):
        Frame.__init__(self, )
        self.hig, self.wid = geom

        # Payment valor presente
        self.it1 = ttk.Label(self, text='Payment Valor Presente', font=font.Font(size=12))
        self.it1.place(x=0, y=20)
        self.it2 = ttk.Label(self, text='Saldo inicial')
        self.it2.place(x=0, y=80)
        self.it3 = ttk.Label(self, text='Saldo final')
        self.it3.place(x=0, y=100)
        self.it3 = ttk.Label(self, text='Saldo final')
        self.it3.place(x=0, y=120)
        self.it4 = ttk.Entry(self, textvariable=0, width=13)
        self.it4.place(x=90, y=80)
        self.it5 = ttk.Entry(self, textvariable=5, width=13)
        self.it5.place(x=90, y=100)
        self.it5 = ttk.Entry(self, textvariable=5, width=13)
        self.it5.place(x=90, y=120)
        self.it6 = ttk.Button(self, text='Calcular')
        self.it6.place(x=0, y=150)
        self.it7 = ttk.Label(self, text='Resultado')
        self.it7.place(x=90, y=153)

        # Payment Valor Futuro
        self.tdi1 = ttk.Label(self, text='Payment Valor Futuro', font=font.Font(size=12))
        self.tdi1.place(x=200, y=20)
        self.tdi2 = ttk.Label(self, text='Interes:')
        self.tdi2.place(x=200, y=80)
        self.tdi3 = ttk.Label(self, text='Credito')
        self.tdi3.place(x=200, y=100)
        self.tdi3 = ttk.Label(self, text='Credito')
        self.tdi3.place(x=200, y=120)
        self.tdi4 = ttk.Entry(self, textvariable=0, width=13)
        self.tdi4.place(x=290, y=80)
        self.tdi5 = ttk.Entry(self, textvariable=5, width=13)
        self.tdi5.place(x=290, y=100)
        self.tdi5 = ttk.Entry(self, textvariable=5, width=13)
        self.tdi5.place(x=290, y=120)
        self.tdi6 = ttk.Button(self, text='Calcular')
        self.tdi6.place(x=200, y=150)
        self.tdi7 = ttk.Label(self, text='Resultado')
        self.tdi7.place(x=290, y=153)

        # Gradiante Positivo
        self.ctis1 = ttk.Label(self, text='Gradiante Positivo', font=font.Font(size=12))
        self.ctis1.place(x=0, y=220)
        self.ctis2 = ttk.Label(self, text='interes simple', font=font.Font(size=12))
        self.ctis2.place(x=0, y=240)
        self.ctis3 = ttk.Label(self, text='Interes Periodo1')
        self.ctis3.place(x=0, y=280)
        self.ctis4 = ttk.Label(self, text='Perdiodo 1')
        self.ctis4.place(x=0, y=300)
        self.ctis5 = ttk.Label(self, text='Periodo 2')
        self.ctis5.place(x=0, y=320)
        self.ctis5 = ttk.Label(self, text='Periodo 2')
        self.ctis5.place(x=0, y=340)
        self.ctis6 = ttk.Entry(self, textvariable=0, width=13)
        self.ctis6.place(x=90, y=280)
        self.ctis7 = ttk.Entry(self, textvariable=5, width=13)
        self.ctis7.place(x=90, y=300)
        self.ctis8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctis8.place(x=90, y=320)
        self.ctis8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctis8.place(x=90, y=340)
        self.ctis9 = ttk.Button(self, text='Calcular')
        self.ctis9.place(x=0, y=370)
        self.ctis10 = ttk.Label(self, text='Resultado')
        self.ctis10.place(x=90, y=373)

        # Gradiante Negativo
        self.ctic1 = ttk.Label(self, text='Gradiante Negativo', font=font.Font(size=12))
        self.ctic1.place(x=200, y=220)
        self.ctic2 = ttk.Label(self, text='interes compuesto', font=font.Font(size=12))
        self.ctic2.place(x=200, y=240)
        self.ctic3 = ttk.Label(self, text='Interes periodo1')
        self.ctic3.place(x=200, y=280)
        self.ctic4 = ttk.Label(self, text='Periodo 1')
        self.ctic4.place(x=200, y=300)
        self.ctic5 = ttk.Label(self, text='Periodo 2')
        self.ctic5.place(x=200, y=320)
        self.ctic5 = ttk.Label(self, text='Periodo 2')
        self.ctic5.place(x=200, y=340)
        self.ctic6 = ttk.Entry(self, textvariable=0, width=13)
        self.ctic6.place(x=290, y=280)
        self.ctic7 = ttk.Entry(self, textvariable=5, width=13)
        self.ctic7.place(x=290, y=300)
        self.ctic8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctic8.place(x=290, y=320)
        self.ctic8 = ttk.Entry(self, textvariable=5, width=13)
        self.ctic8.place(x=290, y=340)
        self.ctic9 = ttk.Button(self, text='Calcular')
        self.ctic9.place(x=200, y=370)
        self.ctic10 = ttk.Label(self, text='Resultado')
        self.ctic10.place(x=290, y=373)

        # Gradiante Escala
        self.vfis1 = ttk.Label(self, text='Gradiante Escala', font=font.Font(size=12))
        self.vfis1.place(x=400, y=220)
        self.vfis3 = ttk.Label(self, text='VP:')
        self.vfis3.place(x=400, y=280)
        self.vfis4 = ttk.Label(self, text='i')
        self.vfis4.place(x=400, y=300)
        self.vfis4 = ttk.Label(self, text='n')
        self.vfis4.place(x=400, y=320)
        self.vfis4 = ttk.Label(self, text='n')
        self.vfis4.place(x=400, y=340)
        self.vfis5 = ttk.Entry(self, textvariable=0, width=13)
        self.vfis5.place(x=490, y=280)
        self.vfis6 = ttk.Entry(self, textvariable=5, width=13)
        self.vfis6.place(x=490, y=300)
        self.vfis6 = ttk.Entry(self, textvariable=8, width=13)
        self.vfis6.place(x=490, y=320)
        self.vfis6 = ttk.Entry(self, textvariable=8, width=13)
        self.vfis6.place(x=490, y=340)
        self.vfis7 = ttk.Button(self, text='Calcular')
        self.vfis7.place(x=400, y=370)
        self.vfis8 = ttk.Label(self, text='Resultado')
        self.vfis8.place(x=490, y=373)

# End Document
